[package]
name = "streamduck-core"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
streamduck-derive = { version = "0.1.0", path = "../streamduck-derive", optional = true }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.58"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
futures = "0.3.25"
toml = "0.5.9"
image = "0.24.4"
once_cell = "1.16.0"
dirs = "4.0.0"
tracing = "0.1"
hidapi = "1.4.2"

[features]
default = ["derive"]
derive = ["streamduck-derive"]