name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Prerequisites
      shell: bash
      run: |
          sudo apt update
          sudo apt-get install libusb-1.0-0-dev libxdo-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
